### PR TITLE
Only add binlog-space-limit for percona image

### LINKED ISSUE #591: Unknown variable "binlog-space-limit" error when using mysql:5.7 image.
Installed the cluster following [this](https://www.presslabs.com/docs/mysql-operator/deploy-mysql-cluster) docs. I am using the `mysql:5.7` image instead of the default `percona` MySQL image. I've also set volumeClaim in `volumeSpec` the cluster yaml, following [this](https://www.presslabs.com/docs/mysql-operator/deploy-mysql-cluster/#persistent-volume-claim). But using this combination of image & own volumeClaim results in the following error:

```
2020-08-24 21:15:24+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.31-1debian10 started.
2020-08-24 21:15:24+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
	command was: mysqld --verbose --help
	2020-08-24T21:15:24.711860Z 0 [ERROR] unknown variable 'binlog-space-limit=341M'
2020-08-24T21:15:24.717024Z 0 [ERROR] Aborting
```

I tracked the issue to the code here https://github.com/presslabs/mysql-operator/blob/288131ec062a1165c51562073b28443dbf59f26f/pkg/internal/mysqlcluster/defaults.go#L99

The variable "binlog-space-limit" does not exist for MySQL 5.7 config. Can this check on volumeClaim to set the variable "binlog-space-limit" be restricted to percona images only?

Operator version: 0.4.0

### PR DESCRIPTION
**Pull request by bananaappletw**
closes/fixes #591

---
 - [x] I've made sure the [Changelog.md](https://github.com/presslabs/mysql-operator/blob/master/Changelog.md) will remain up-to-date after this PR is merged.

### CODE REVIEW

File: pkg/internal/mysqlcluster/defaults.go [hunk 1]
```diff
@@ -105,8 +106,10 @@ func (cluster *MysqlCluster) SetDefaults(opt *options.Options) {
 				maxBinlogSize = min(binlogSpaceLimit/3, 1*gb)
 			}
 
-			// binlog-space-limit = totalSpace / 2
-			setConfigIfNotSet(cluster.Spec.MysqlConf, "binlog-space-limit", humanizeSize(binlogSpaceLimit))
+			if matched, err := regexp.MatchString("([a-z.]+/)*percona(:.+)?", cluster.Spec.Image); err != nil && matched {
```
Comment (AMecea) [inline pkg/internal/mysqlcluster/defaults.go:109]: Let's define a utility function `IsPerconaImage` that will try to identify the source of the underlay image. Here is an example: https://github.com/presslabs/mysql-operator/blob/677a2ce5d364270604b8a0645e19a7df742f36f1/pkg/internal/mysqlcluster/mysqlcluster.go#L224

Also, please use `GetMysqlImage()` which computes the image based on more rules.

```suggestion
			if cluster.IsPerconaImage() {
```

**Review by AMecea — CHANGES_REQUESTED** [review]

**Comment by bananaappletw** [comment]
@AMecea 
Changed.
Please review again, thank you.

**Review by AMecea — APPROVED** [review]
