### PR TITLE
Keep last known state when orchestrator is down

### LINKED ISSUE #203: Master service fails when orchestrator is down
The rebooted node failed with the following message:
New IP of rebooted node:  10.233.5.244
Old IP before rebooted: 10.233.5.243
Other nodes without rebooted: 10.233.0.160 and 10.233.17.75

- Rebooted node side
```
2019/01/15 04:52:56 [INFO] raft: Node at 10.233.5.244:10008 [Follower] entering Follower state (Leader: "")
2019/01/15 04:52:58 [WARN] raft: Heartbeat timeout from "" reached, starting election
2019/01/15 04:52:58 [INFO] raft: Node at 10.233.5.244:10008 [Candidate] entering Candidate state
2019/01/15 04:52:58 [WARN] raft: Remote peer 10.233.0.160:10008 does not have local node 10.233.5.244:10008 as a peer
2019/01/15 04:52:58 [WARN] raft: Remote peer 10.233.17.75:10008 does not have local node 10.233.5.244:10008 as a peer
```
- existed nodes side
```
019/01/15 04:55:55 [DEBUG] raft: Failed to contact 10.233.5.243:10008 in 3m59.07956023s
2019/01/15 04:55:56 [DEBUG] raft: Failed to contact 10.233.5.243:10008 in 3m59.528575654s
2019/01/15 04:55:56 [WARN] raft: Rejecting vote request from 10.233.5.244:10008 since we have a leader: 10.233.17.75:10008
```

 The rebooted node failed to join the existed cluster because
- **the ip of rebooted node had changed**
- **other nodes keep the old ip of rebooted node**

### PR DESCRIPTION
**Pull request by AMecea**
fixes #203

### CODE REVIEW

File: pkg/orchestrator/errors.go [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+		HTTPStatus: 0,
+		Message:    msg,
+		Path:       path,
+	}
+}
+
+// IsNotFound checks if the given error is orchestrator error and it's cluster not found.
+func IsNotFound(err error) bool {
+	if orcErr, ok := err.(*OrcError); ok {
+		if strings.Contains(orcErr.Message, "Unable to determine cluster name") {
```
Comment (calind) [inline pkg/orchestrator/errors.go]: Check for other not found erros (eg. nodes).

File: pkg/orchestrator/errors.go [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+import (
+	"encoding/json"
+	"fmt"
+	"io/ioutil"
+	"net/http"
+	"strings"
+)
+
+// OrcError contains orchestrator error details
+type OrcError struct {
```
Comment (calind) [inline pkg/orchestrator/errors.go]:
```suggestion
type Error struct {
```
