### PR TITLE
Fix backup under stress

### LINKED ISSUE #256: Backup issue when continuously inserting rows.
While doing insert queries to mysql cluster, i tried to take backup in parallel. For 2gb data backup size was 43MB and for 200GB data backup size was 33MB. And when i tried to restore the cluster from the backup file it got stuck with STATUS: Init:1/2.

### PR DESCRIPTION
**Pull request by AMecea**
fixes #256

### CODE REVIEW

File: pkg/sidecar/server.go [hunk 1]
```diff
@@ -79,6 +79,7 @@ func (s *server) backupHandler(w http.ResponseWriter, r *http.Request) {
 
 	w.Header().Set("Content-Type", "application/octet-stream")
 	w.Header().Set("Connection", "keep-alive")
+	w.Header().Set("Trailer", "Success")
```
Comment (calind) [inline pkg/sidecar/server.go]: Let's prefix our trailers with `X-` so that we don't interfere with possible future common trailers. We should also move from `Status: true/false` to `Success` and `Failed`.

```suggestion
	w.Header().Set("Trailer", "X-Backup-Status")
```

File: pkg/sidecar/server.go [hunk 2]
```diff
@@ -137,3 +140,49 @@ func maxClients(h http.Handler, n int) http.Handler {
...
+			status = resp.Status
+		}
+		return nil, fmt.Errorf("fail to get backup: %s, code: %s", err, status)
+	}
+
+	return resp, nil
+}
+
+func checkBackupTrailers(resp *http.Response) error {
+	if values, ok := resp.Trailer["Success"]; !ok || !stringInSlice("true", values) {
```
Comment (calind) [inline pkg/sidecar/server.go]:
```go
const (
    backupStatusTrailer = "X-Backup-Status"
    backupSuccessfull   = "Success"
    backupFailed        = "Failed"
)
```
