### PR TITLE
Fix remote storage delete bug. Fixes #352

### LINKED ISSUE #352: Cannot delete MysqlBackup when RemoteDeletePolicy is delete
version: 0.3.0

The args of Delete container in pod is  `rclone  --config=/etc/rclone.conf  delete path`, 
while in sidecar-entrypoint.sh I found `cat <<EOF > /tmp/rclone.conf`,  delete container should use `/tmp/rclone.conf`.

If you need help, just tell me which branch should I post.

container log:
```
Create rclone.conf file.
Create google-credentials.json file.
Usage: /usr/local/bin/sidecar-entrypoint.sh {files-config|clone|config-and-serve}
Now runs your command.
rclone --config=/etc/rclone.conf delete s3:/mysql/test/test-zotwe-auto-2019-06-13t02-02-00-2019-06-13T02:02:00.xbackup.gz
2019/06/13 02:27:11 NOTICE: Config file "/etc/rclone.conf" not found - using defaults
2019/06/13 02:27:11 Failed to create file system for "s3:/mysql/test/test-zotwe-auto-2019-06-13t02-02-00-2019-06-13T02:02:00.xbackup.gz": didn't find section in config file
````

Job Pod:
```
Name:               test-zotwe-auto-2019-06-13t02-02-00-backup-cleanup-6mpkp
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               bluven-k8s-3.novalocal/10.20.9.14
Start Time:         Thu, 13 Jun 2019 10:22:16 +0800
Labels:             controller-uid=0a3330da-8d82-11e9-b5a0-fa163ea41f47
                    job-name=test-zotwe-auto-2019-06-13t02-02-00-backup-cleanup
Annotations:        <none>
Status:             Failed
IP:                 192.168.233.248
Controlled By:      Job/test-zotwe-auto-2019-06-13t02-02-00-backup-cleanup
Containers:
  delete:
    Container ID:  docker://c9e8b2c00695f7601a94bb7c41882a3927b9e3c5bce25899f9bc513ac8e6160d
    Image:         registry.bluven.me:5000/bocloud/mysql-operator-sidecar:0.3.0
    Image ID:      docker-pullable://registry.bluven.me:5000/bocloud/mysql-operator-sidecar@sha256:de8c572fc885a37605deed5cac71629c48a70dcb259922e1f447aebd897f0c3b
    Port:          <none>
    Host Port:     <none>
    Args:
      rclone
      --config=/etc/rclone.conf
      delete
      s3:/mysql/test/test-zotwe-auto-2019-06-13t02-02-00-2019-06-13T02:02:00.xbackup.gz
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 13 Jun 2019 10:22:19 +0800
      Finished:     Thu, 13 Jun 2019 10:22:19 +0800
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      test-zotwe-backup  Secret  Optional: false
    Environment:         <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dndgt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-dndgt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dndgt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                             Message
  ----    ------     ----  ----                             -------
  Normal  Scheduled  10m   default-scheduler                Successfully assigned default/test-zotwe-auto-2019-06-13t02-02-00-backup-cleanup-6mpkp to bluven-k8s-3.novalocal
  Normal  Pulled     9m    kubelet, bluven-k8s-3.novalocal  Container image "registry.bluven.me:5000/bocloud/mysql-operator-sidecar:0.3.0" already present on machine
  Normal  Created    9m    kubelet, bluven-k8s-3.novalocal  Created container
  Normal  Started    9m    kubelet, bluven-k8s-3.novalocal  Started container
```

### PR DESCRIPTION
**Pull request by bluven**

### CODE REVIEW

File: pkg/controller/mysqlbackup/internal/syncer/deletionjob.go [hunk 1]
```diff
@@ -18,6 +18,7 @@ package syncer
 
 import (
 	"fmt"
+	"github.com/presslabs/mysql-operator/pkg/util/constants"
```
Comment (AMecea) [inline pkg/controller/mysqlbackup/internal/syncer/deletionjob.go]: This should be in the last block of imports (a few lines below)
